name: release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Run "release-please"
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: magnum-cluster-api

      - name: Checkout project
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        uses: vexxhost/maturin-action@add-missing-env
        with:
          command: publish
          args: --non-interactive
